#ifndef CW_ERRORS_H
#define CW_ERRORS_H

#define INVALID_OPTION_ERROR 40

#define NO_REQUIRED_OPTIONS_ERROR 41

#define INVALID_OPTION_ARG_ERROR 42

#define INCORRECT_BMP_FORMAT_ERROR 43

#define FILE_ERROR 44

#define MEMORY_ALLOCATION_ERROR 45

#endif //CW_ERRORS_H
